version: "3"
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - nginx
    volumes: 
      - ./:/app
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - .env
    environment:
      ENVIRONMENT: production
      GIN_MODE: release
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"

  database:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "43780:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/letsencrypt:/var/www/letsencrypt
    ports:
      - "80:80"
      - "443:443"
